In [1]:
## 경고 제거##
import warnings
warnings.filterwarnings('always')
warnings.filterwarnings('ignore')

## DataFrame & visual option ##
import pandas as pd
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))
pd.set_option('display.max_columns', None)
import polars as pl

import numpy as np
import os
import json

## geo ##
import geopandas as gpd

## Visualize option ##
import seaborn as sns
import matplotlib.pyplot as plt
import ipywidgets as widgets

plt.rcParams['axes.unicode_minus'] = False
plt.rcParams['font.family'] = 'D2Coding'

In [75]:
import scipy.stats as stats
import pandas as pd

# 가상의 데이터 생성 (예시)
data = pd.DataFrame({
    'Category': ['A', 'B', 'A', 'B', 'A', 'B'],
    'Numeric': [10, 20, 15, 25, 12, 18]
})

# 명목형 변수를 이진 인코딩으로 변환
data['Binary_Category'] = (data['Category'] == 'A').astype(int)

# pointbiserialr 함수로 포인트-비스레 상관계수 계산
correlation_coefficient, p_value = stats.pointbiserialr(data['Binary_Category'], data['Numeric'])

print("Point-biserial correlation coefficient:", correlation_coefficient)
print("P-value:", p_value)

Point-biserial correlation coefficient: -0.8628403050799637
P-value: 0.026928995152111498

# PC학과

# 기능

In [39]:
TexamD = pd.read_csv('../../../011.데이터/00.스키마및샘플/MTS_TAAS_면허/3.면허/도로주행/1_2종/ExamDetail.csv')
TexamM = pd.read_csv('../../../011.데이터/00.스키마및샘플/MTS_TAAS_면허/3.면허/도로주행/1_2종/Exam.csv')

In [71]:
for i in TexamM['ResidentNo'].unique():
    if TexamM[TexamM['ResidentNo'] == i].shape[0] >= 2:
        print(i)

9002021033017
8111061009011
8502201052021
5601211541011
9403102853221
9001282034626
8806201163412
8907221083118
9503171704210
9608171074913
8805165220024
8309021547517
7703201800914
5511131229115
9506301824314
8312281032416
7811301665913
9710191036613
8212256500198
9804102082511
5504122025634
110203020820
9509162122319
9309215280023
8603221074519
9906181170718
9309021069320
8009021237511
9803141017613
9302161111024
8108131080315
9209231081414
7711202177512
9273162718
8802171231643
8109212037513
104174063022
1243081635
9308301065636
9904121010010
9211202155025
9701092170237
8511131334818
9809241006711
9708031021118
9707311083315
9406081168327
9805301216321
9401082567413
107043214411
9012022018726
7809152659411
9604202902512
8701172205515
9402232081322
9402222156322
4303078223
8202091652414
9707281541019
3074168018
9909011168511
6802295920020
9902152020122
7111015100029
8801012148711
1043085614
9012132237113
1034041911
9005292394311
8103072521
5604011069814
7205085100027
6510281390915
9601252080711
9602042032328
9307041163735
6206031455117
11143053120
8204131032320
9709261082627
8709282074812
5406191009131
7908142080813
7509291080211
8301021055817
8209111644115
8508061057317
9206032194616
9501172069011
9301282824416
8907182155931
9711031078311
9508091042012
8810201710810
7509161468722
9704131411718
7711231321211
9803241047821
9212052067710
9208111078222
8711041082716
9602052035713
8604031024518
9308115920118
9201281011016
9607011483717
9912241019910
108303170211
101013222538
1033036622
9309261068118
9505172074015
6911201229618
8905172850837
8011282360513
9309222023310
8101272080811
9910021157127
9911011483039
8708086100133
6105252024915
4605101041316
9205162840512
9601085760223
9511201174317
7712291541111
8501251019711
6410021029423
8509161066825
109273051110
8612272644015
9804261167928
7502075102391
9106302170510
5510281533913
9102231169621
8811232169723
8205301070711
9206122247311
4909131830310
9112221200129
9309041675829
6008081820812
9405136780135
9406031034825
8104102011614
8203185000000
8908192187311
9612232209314
9507231830315
9109201853559
110233401910
103313237719
9712166760014
9406291001611
8211142047614
5710131167628
8708142170212
9905192482028
6708012451238
6701071074817
5601162221821
9704181079118
9405311083216
9205211081720
8101205000000
7601071811213
102143249521
9307272267718
9309116780148
9712176700019
9004112331119
9804242177511
9912271017810
8809012357314
5512011056610
9402141074226
9401102011025
7301301064821
8710241170111
8605211057324
5606061036620
8810071521017
8305031178235
108293055410
9211112478829
10034020011
106173180118
7503245100038
9312192481027
4183057812
9912011020411
7611145100036
9207065100069
6301051467229
9301252067811
103313495813
8003121056920
2203496638
7801301815012
7207052004916
8405141829219
9609142081714
9304261032321
9206112162315
8412045100179
7706171009314
9908071076114
9105301169711
8905151047611
10194179517
7509172031219
5511031251213
9106192013119
9008221074511
7106216140019
9803061078719
8201311482121
9903191419327
9409042901812
1253561717
6103183416
8001312837228
9008312034511
8012022357318
7705111540815
9604122170513
9106052167426
6404181328813
7112121663410
5908141551821
9901291184417
9001181067011
103043245015
9303282222427
9607041053118
9007176100018
8202201231020
9803262171321
9902032081710
9808051074622
5406171047320
9507221020618
9411171006210
9710071074716
9807226100013
9102051017317
9910106780013
8211252474516
6109271394615
8009171025711
7608022019129
5904241243227
4103933110
1013058514
9509031058211
9104122101015
8405232902111
9303302082711
8602166200793
9009201019238
9205141081518
9610291077215
9507062121316
9908032080715
9602292071016
5311081019219
7010245300194
9505292074321
9608142167515
6101231346311
8308122011116
9202051209411
8007301079617
7214865819
8810052079423
8302221081016
8902251245117
9607021018023
9809201095638
9612202169610
8710182168920
6803122080124
9609091850110
8503012074623
9010242009923
9504212009716
9507222069528
9608231069911
7005011529023
9705311169537
9304272078713
9812131268719
9308112083021
6508042528227
9603111075014
7512071333412
9402022352110
8706212496018
9511151066112
9509191560419
4273020615
6102241406421
8802161075029
9011246100127
8608271018418
9209201169716
6210241006726
9412052691812
9805122200219
104033065714
7111271540417
4908261052711
8312101162723
9603222170528
9002241743537
9310062179319
9605285100037
9011031018118
9707091078623
9006241080410
5708125100783
9705232069317
9911251124014
8603051637019
9509271020211
8506101082114
11203076614
6512301490817
7102051652323
9801081236615
9212221216518
9105011080112
110243076717
9510012032213
9610062018718
9124164018
7203191470713
7710051017811
8211271030639
8806081951526
9912281018319
7104071894413
9402212025026
7209171398711
8906302034925
9405192352943
9508281528410
9208062069010
7904275100103
8804285101194
9811021932613
9712155100018
9603116100141
6611202047121
8510286100054
9206022178316
101063006012
6023077311
8706202168318
9503071078711
6809251068010
8909291063311
6404152393111
9605032056919
9710171403115
9612161082938
7510225000000
9801181162411
9405072079319
9709172065811
9302192067015
9312242417111
5103071042128
8209011695813
9712211074623
8509281168920
9710041727217
8606125000000
6705021545417
9607042011316
9404241178410
9909202168728
5701101063828
9503261076017
9802172477917
9601311058616
9602052168017
8408111042910
8807085100126
8404155100145
9211262009018
8506165000000
9101102216120
103263080425
9810311121116
8901021068735
9805276780037
8104231675413
8611122041724
9109191187719
7902062677219
108073067011
9104091250024
8710235760891
6309091472011
9803181005412
9406131213814
9106021249417
8209031067825
9912106100017
9807041663218
9043082114
8208142048314
8263078628
6605076000000
8101141004912
9309261070311
9510081074117
9910062171816
9408021017812
9501011169516
7408091069518
8903132079412
9303152020910
8801036100154
7702261074244
9605172550822
9293245211
9701202164811
9505292078411
9902021646013
9603081702511
8602191074626
9306172748611
8902252574518
7609172904615
9412212185413
6605032655512
8510212046115
7402201905921
8510081013016
106273067916
9603201251718
9101042020019
8601241222417
7709131227119
9908161081310
7601135000000
9707031037915
101313079316
6906252196111
105133076710
8203062030911
9109041951712
8201192169416
7310052632111
6009272243119
8007292822311
9410072865913
9209262047814
9409241897723
9104032820711
9801152068729
9901082233218
9701312069013
9712131865411
9009052077229
9807156760019
8910281013014
9003161575317
9503101179815
101284410216
9911031067229
9702146760011
8301186000000
9309105860020
9701261082714
9303041034547
9507141075826
7010255000000
9410252085212
5912121019018
9206161082817
9310192019217
8606072177810
9607111077026
10173019719
9901152079812
9304251490313
8509051082728
6107101624516
9103221178010
9303091075017
9307221080410
9208072069216
106154031610
5243079637
9701102031819
7607101019711
9210241002513
9810041075912
9610261082515
5712122222316
9708036780012
6312311347926
9811051216112
9011151069716
9402171179818
9204042057114
9802021035010
9909271079815
9102021626617
108013274211
9210051031911
9907051081519
8811122012311
9905016280013
8206031081411
9212052050219
9303302047416
8810011168011
9306241064921
9611281045111
9903261170014
9508291586012
9902041081518
9508031023919
8302031775126
9701081074014
9410101216018
9103111069420
7306021052814
9610191075835
9410042078715
6207031005525
8005162792118
111023067421
6508271067012
9010261552911
8808231243612
8210072249629
9611231409512
9010212119714
5905091336937
9105182055011
9507091078314
9103141076411
9801192032411
8207231051816
6508201394816
9109231668210
3053328115
9202142805421
9011151652515
9809021081212
8909022070219
2284070627
3043068327
9408102228512
9208291068319
9703251401513
9009151548217
9707291664215
9609051170028
9609161055713
9703181222429
9603081068318
9112222560111
9702171017110
10203168136
9012242550518
9805042081510
7206261047141
9710021337429
9003021079617
8508011149616
9812201123113
8705306000000
5223203237
9302101077510
102013469510
9909271165414
9504012046125
2083077311
9009112199221
8709101057011
9002041018927
9504222164511
9707092047416
7011011464818
8411175000000
7212121394322
7608021852325
9703241850227
9902062080511
12184080515
9910291352914
5505231558417
9306202018912
8404151520515
9503241070336
9006211055426
6106211119913
9405111059515
9207222184757
6702202658860
8809222082011
8910201240716
9610085100043
9509152051513
8307161019612
9305141069111
9206221123817
9309162235914
9401211075312
8408062079911
6108261674412
9801125920013
9407251030529
9511241070625
9704071078411
9105171020419
8407102056515
9805061933514
12123170311
8602271032717
9503022168313
7908111075231
9707181237126
6802285120592
9303101052715
9405231082019
8609101091012
9701142406417
9108302127526
9112242017221
7404301636511
8208071075919
5612105000000
8309281006551
7110171642921
8411052079916
9512175100047
9111061201111
9806172077222
9711131075815
6604245141896
7009195100176
9901031216319
9504032081711
8408142224317
6106241627922
7402191454811
7204095000000
9610032170111
9311132227816
105293403319
8609301178338
7103255101498
102233001917
8810211177422
9608132019513
9102051019418
9407182384112
9710221419412
7003111017415
9302282009220
9706182035013
9303111070128
8411282076449
8606052466311
9101301726721
9310021168017
9204046640028
8709191335114
9412212081433
8112112149639
9110302157315
9702032030626
12213219011
9802131068516
9312231082513
8703115000000
101313326212
9501232080813
9709181075319
8708022267626
7408011081111
9410111069117
9508212070522
8807082020414
9407302194918
7207252029310
10133018829
8611011237514
9810216780061
8806065000000
108183029619
9006181674711
2033165451
9512211236619
9510241043237
6410011540729
8905202082526
5511151009614
6604162019219
9101171071121
9209231850828
8208055000000
9811291082014
9809272185624
9412281017219
9610052077417
5905051639214
8602051559514
9501061212717
9701091019710
8801231075011
7701081068414
9005192118018
7314474614
103063078816
106073052816
9706052201114
9706181226814
9401121030013
9802276700020
9609092199716
8602131051829
11273419326
9805271023512
9802031074414
7906212001914
6803151801017
6912042119723
6811031168018
9409051069611
8709152018112
9804271628611
7103261657627
9902042457218
9404031558717
9102161024910
7507291696011
9410131188617
9305092018820
6401281800111
5208201929522
102283077318
9009211020229
6509181466316
9604042083012
6701131221134
9303282068729
9607021077010
9702252072711
9810121079214
7510091025222
7003121468617
7301305100027
9311041047724
7109132229315
8501036000000
9001271081320
9410121067618
9309261409210
9808142077410
9510191167719
7903211538717
7710161066910
8508135920036
9809082188210
9404082703116
9601032235233
9206142905911
9701291018017
9602191006317
110083011423
8003101002116
8602091466311
9706191203318
9805302034317
8302152352061
9905211081721
104163070615
9512261218615
7001201321917
9507251058013
110123187712
12183069618
8507241227013
5501201052321
104194496616
106223083018
107054034521
7501161024116
7210021093811
9404302677916
7110275140027
7211041653011
7904272058618
6004221222619
6063222515
104093222437
9808031218710
9410062674415
9308041214216
8211272065110
9301181079614
8807035000000
8701062167818
8802021012515
6304195102497
9607171697943
9305252726111
8805131823525
9612265100030
8901271903510
7502201000611
8010251235012
109253075513
110233068218
9504171083211
8105301032118
6401131659411
9901302212219
5502161080019
8312271079721
107104076712
8812301169415
8902251530919
9301261561315
101303328918
9010072042014
110163050411
9808301854124
9703091009712
8812215101098
9805301333419
8910191163518
108213069215
9605181034512
7208121483011
6202051011428
5801201345818
111083222412
9801041076919
9601252411911
9308272042423
9702252179115
9406226100205
111123017313
7303225000000
111093053019
9206171178316
9501091068521
106183020911
9803041273111
5907171006022
9909031334711
7909031085312
8207232551017
8603032685918
6306181333413
5023002611
7205251155719
9905182157710
7501311041629
8801261167416
9406302079926
9710021140919
7503151815026
7402111174124
9110301052613
9905022408310
9407121081612
9205305100054
6601251580622
9802122033119
9809051157214
6807182542818
9811022080317
103083037119
9303152010410
3163024418
101288100049
9810041034816
6911281006038
8205095101596
9411301183224
7903242011811
9307022072815
9802086100039
9212122149713
9404141419419
9108142674311
9509115920012
9604151012424
9903156100035
9905165100592
7227100013
9506301406224
9809265760021
8293035325
2243201212
9711021200614
6707151663326
5703261019011
8712101151524
9903141032311
9611082078218
8105031074230
8312052915517
9509161068919
103113168015
9310151169415
9501212081717
9405121058714
9305022860613
9109302504312
9510186120060
9411142047511
9403101852722
9203136100149
8201241187518
9502142077121
9504121209311
8083081010
9008181807816
6903201053123
9206151041514
9110082170113
9607251019517
8403171071014
9002131081513
6603145220010
6612202348022
9605061254318
8607131113814
8704172157611
8012051473711
103293247342
9504062082522
7305242253824
9712011065714
9810271020712
9009206100120
11084081512
9501111030839
9305155200123
9705301216324
7109171063611
9307262457218
9807121170811
8612212496629
9504271067015
9807222068314
8907262559113
9711062069111
9510111195127
5811145140592
9204221096119
9601172032926
6254449332
9207272079517
9209162063518
9901031019510
9008205100393
104133074111
6502212659317
9010221001119
6109231454716
111124056910
9507291078719
8403142069822
6005151009110
9202031081311
6108011052226
6908282520237
102133041616
9403172019911
9506302457210
9411151005925
9804291051119
9612041066918
8608215920067
8401292411315
9708276100024
9602192001911
9001012122225
4809051010821
108153067824
105183012218
9611042078331
9211161020812
8301171025745
7103071777219
9309281068937
9109122017221
4074223711
4258140013
9811172045014
9701072768316
9705101074610
7802161000417
5708091036111
8201081070213
7411282069119
9902202047516
7906101120519
9409271055611
7407192056712
9912142074911
8609191079615
6711271009923
8808232235424
9006301685220
9401041011225
5704041030011
7909225000000
9911122393127
8601062052814
9905145760199
8802101019123
6701192010012
9707241081510
6412235100024
8506272635215
9505231178312
8301141260216
8603301182922
9711261748116
8711191063223
9508042071313
8006251352111
7510191051521
9507252071919
9210012083621
8109231002021
9505302209311
9405132235311
9602211074112
9902035780026
9402222053111
9612122179311
8708152031822
8309201001812
9201271019026
9103282156221
2153171329
8310142169512
9404105000000
10103170911
8207062023116
9910212080725
8708242573820
8106175101495
7403241268224
9610311074016
9909026700028
7009251057111
8302032360218
9009051168019
8207282018719
6210105104496
9311261082727
7406122005318
9604271170311
8901202019624
3013055417
9802092171820
7602012927331
9805021261431
9412151155122
9905141069734
9706196100032
8601031496211
9603112624511
9601181074513
9512152079821
8409292545912
9406032017316
9710132035617
9001292081710
8806092080411
4054201413
9705271070910
9102061080114
5603141932111
9702102070019
9606011052114
7402281548313
104124207119
9201211030922
8411051085218
107103071916
9402081019021
9805101006016
9710041035816
9508292187710
9506161721612
9212141203115
9110311192237
9402161030013
9708136780063
9107151030522
6511301005913
8106171074351
7902091917117
9811242199025
8704082691811
8905276220293
8001041029913
9509011201423
9707121011729
8133853512
8105021124814
9001011077116
9112251235638
8004231024422
3313069418
9509016100227
106303055218
9209236100216
8812176100059
9906041083028
9309092078724
108193006016
8211221187816
107063078519
6812011005419
9810091006515
8104131647926
104093021121
9201042183323
8508181052718
8301172473619
6209181653115
8311081182435
8503236100899
7005195100036
11133222523
5303221001513
9909171162611
8011231178611
106293728221
9304262018315
8507026100110
9507021905914
6003261079915
8304015100037
7809012249241
104208100025
6073076718
9408141179810
7510165700011
107054075612
7802011036615
105213167515
8702031054017
9902061066820
8908251184210
9707272167512
9409222861715
9812151067416
9604141070126
5123045119
107063409410
9908205780012
9405092932116
4403051241318
8311185000000
8802292058865
7609145100374
9602081010111
8905222168710
9509015120013
9401212120715
5507251031521
9912221076028
8312152127317
9903281068714
7048100014
9510021183716
9204232019629
8204031547927
9310132345911
9502281850515
8911281279817
8512211163718
101223249522
8604225000000
9906211080019
9804211053114
8910012458617
9405242079712
8301152252321
101293748423
9101042149834
9807101164820
102223067030
8711102656917
9406152076325
9805281013112
9501272081111
9502041170221
102023209318
9809012020119
4283070919
103154560417
8508162187118
4103021111
9809301075113
106108100022
9203111067027
8909271064123
8502201067811
9706041079419
9801262011816
8801066100210
5502181534110
5204111006712
8003011927231
9805162068612
9311111033026
6009061001523
9708252222123
9705141068727
9209262170232
6106011663718
8107171006521
9806021122328
9705292853012
3163165425
109283011329
9410155780027
9604152082013
108073067619
9905032076811
9501206100011
7301261820912
103233167415
9608062017216
101033411918
5304168615
9701062187737
101073051715
7904216000000
111043072811
8403041025615
10087100111
9606092010813
9504251081325
104093081318
103234018711
8812022063923
9502192069516
9510262058712
9408282648211
5410121696613
9709021174317
8210271067212
8804201155423
9609031170411
9109132080910
8904071726415
5407031396512
9302121167617
7801186820025
9305102080815
6512201036435
9707172408917
12223068314
9006192126519
6003011644331
5706291101719
10194218736
7408221642216
5608132030319
9711051179712
8008211574315
4213017525
9124072811
9801096860018
8003012174015
8603181173916
9101201056916
5908032053021
9403292071818
9510282059514
9702035000000
5609251063240
9608122167620
9702111177418
9906112213816
9205302042050
9303131042013
9801116920013
8701015100051
9001262209416
8910122691717
9704212081013
11304180415
9210311170623
6402141396917
6110251018538
9194037916
9009205100106
7003031018623
9508291020213
7411212642918
6193068919
4809031894316
9707051079717
9402071209615
8010131052812
8911292065534
9401311078720
9006075820056
8611162231815
109293209214
112013020617
7603151345349
6803042469417
109193121216
9098100055
9212282246912
9301062076816
9504222080517
8806112006010
8807241816811
9404202006211
9902286780047
9306182018917
9206285000000
9708062580614
9904072213311
8703181157622
9902205760060
8510021663219
9303101114815
9706241698423
9905011249528
9501031125618
7705046000000
9705291021112
9304071152622
8012072951111
9911181067328
9012271081412
6809171628213
7811255000000
9508261076014
9806021083510
9809175000000
105193081211
11023216019
9701051020110
2083083011
7064055014
109293083010
111013170219
6404255102494
103303165617
110213233213
9908231185111
9301241067216
8606156920012
9606041183611
6911152392815
9104131169521
7610011249919
6709251110111
101173076114
8002281328312
8412121019321
9402261020826
9223079611
9612185200034
102023082415
9708121011521
103164031323
9310271500516
8705102069815
7706222010914
9203252621819
7905112065015
8007251058420
7504161012419
6105151019323
9507241388811
9112232617116
9606192180016
9310212393113
6603101816617
8606251937415
9106051638014
9802241170217
3044069722
8706281080417
7601142802448
8105151901912
8701011032312
8107031002015
9209292173721
8206201019410
9001061063310
3023249527
103083079415
105283081319
9908091068610
9812261078815
8810301120011
9602121690911
9306291057117
9812302019114
7404045920059
8705182046710
9912172020911
11133078210
9709292077223
6212185102395
9512031178516
9710275100030
9511172648816
9501152816711
108233241115
9001011020211
108274078413
9210241021011
101314080910
9611262031521
6409132268111
9810192162119
11113179916
9502032174214
8810192052516
9801191042117
8209141637611
6406051047118
9903051018729
9004091070911
7207012347719
109113849417
108103177511
111083169713
9908302228614
5153020310
1074077016
9506276140063
8408121151617

In [73]:
TexamM[TexamM['ResidentNo'] == 8111061009011]

,ExamDate,ClassNo,License,AppNo,Name,ResidentNo,ExamResult,Score,FailCode,WrongCnt,StartTime,EndTime,SpentTime,DataFlag,ExamType,ReceiveTime,SendFlag,SendTime,Subject,OutExamCode,LicenseCod,AcceptNo,HandiFlag,PoliceCode,StudentNo,OfficerID,TestFieldCode,AcademyCode
3,20191022,1,1N,4,DSSqRYFYqqJJIdBBvF+FCQ==,8111061009011,1,82.0,0,NaN,94513.0,95146.0,633.0,T,A,92856,NaN,NaN,2,0,00,-1,0,NaN,NaN,28-00000,0,0
37445,20201124,2,1N,4,W6nyi0sMO15PEU589FYFEg==,8111061009011,6,100.0,0,NaN,NaN,NaN,NaN,T,A,111741,NaN,NaN,2,0,00,-1,0,NaN,NaN,74-00000,0,0
40758,20210113,5,1N,3,uS3An9NU3t7Sulv8Lm1LUg==,8111061009011,2,75.0,0,NaN,151228.0,151950.0,724.0,T,A,150110,NaN,NaN,2,0,00,-1,0,NaN,NaN,78-00000,0,0
41268,20210120,4,1N,4,eWCnR8FcQQnl6qF/86Y0wA==,8111061009011,1,85.0,0,NaN,141656.0,142423.0,727.0,T,A,135830,NaN,NaN,2,0,00,-1,0,NaN,NaN,67-00000,0,0

# 도로주행

In [25]:
DexamM = pd.read_csv('../../../011.데이터/00.스키마및샘플/MTS_TAAS_면허/3.면허/기능/exam.csv',encoding='cp949')
DexamD = pd.read_csv('../../../011.데이터/00.스키마및샘플/MTS_TAAS_면허/3.면허/기능/examdetail.csv')
DexamP = pd.read_csv('../../../011.데이터/00.스키마및샘플/MTS_TAAS_면허/3.면허/기능/exampoint.csv',encoding='cp949')

In [29]:
DexamM

,ExamDate,Class,License,ExamType,AppNo,Name,RegNo,PoliceNo,OfficerID,Score,ExamResult,MapIDs,TLicenseNo,Phone,Rev1,Rev2,Rev3,Rev4,Rev5,EXM_LICEN_NO,RECEIVE_DATE,RECEIVE_TIME,LICN_PRT_DATE,RESIDENT_DATE,RESIDENT_NO,RESIDENT_NAME,RES_PHONE_NO,PROC_EXM_CODE,RES_EXM_CODE,EXM_CODE,RES_CLS_CODE,LICN_CON_CODE,RESPOND_DATE,RESPOND_TIME,RES_START_TIME,EXM_NO,RECV_KIND_CODE,WEB_RECV_OPT,EID,ETestfieldCode,EAcademyCode,EOutTestfieldCode,EReserver,EAcceptNo,ERegNo,EName,EAcceptDate,EFirstFlag,ESubject,ELicense,ELicenseCond,EApplyDate,EApplyClass,EApplyTime,EApplyNo,EHandiFlag,EUnletter,EThoryDate,EThoryScore,EProcessDate,ERelease,ELanguage,ETLicenseNo,EOfficerID,ORev1,ORev2,ORev3,ORev4,ORev5,ORev6,ORev7,ORev8,ORev9,ORev10
0,20170828,1,1N,A,3,이수빈,900314-1000000,NaN,1101413.0,0,3,NaN,6.016061e+10,1.026088e+09,NaN,NaN,NaN,NaN,NaN,6.016061e+10,20170822.0,162335.0,20160901,NaN,NaN,NaN,1.026088e+09,10.0,10.0,00,12.0,00,20170828.0,1.0,900.0,1.0,2.0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
1,20170828,1,1N,A,4,박진화,570123-1000000,NaN,1101413.0,0,3,NaN,6.017024e+10,1.051400e+09,NaN,NaN,NaN,NaN,NaN,6.017024e+10,20170825.0,110026.0,20170825,NaN,NaN,NaN,1.051400e+09,10.0,10.0,00,12.0,00,20170828.0,1.0,900.0,5.0,2.0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
2,20170828,1,1N,A,8,김건욱,921110-1000000,NaN,1307043.0,0,3,NaN,6.017021e+10,1.055588e+09,NaN,NaN,NaN,NaN,NaN,6.017021e+10,20170825.0,94313.0,20170802,NaN,NaN,NaN,1.055588e+09,10.0,10.0,00,12.0,00,20170828.0,1.0,900.0,3.0,2.0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
3,20170828,1,1N,A,11,문영호,660401-1000000,NaN,1101383.0,0,3,NaN,6.017024e+10,1.021126e+09,NaN,NaN,NaN,NaN,NaN,6.017024e+10,20170825.0,94804.0,20170824,NaN,NaN,NaN,1.021126e+09,10.0,10.0,00,12.0,00,20170828.0,1.0,900.0,4.0,2.0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
4,20170828,1,1N,A,12,김지경,950623-1000000,NaN,1101383.0,81,1,NaN,6.017024e+10,1.020048e+09,NaN,NaN,NaN,NaN,NaN,6.017024e+10,20170825.0,125945.0,20170821,NaN,NaN,NaN,1.020048e+09,10.0,10.0,00,12.0,00,20170828.0,1.0,900.0,6.0,2.0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110954,20221103,4,2A,A,16,서성희,840120-2000000,NaN,1112020.0,0,3,NaN,6.022008e+10,1.049990e+09,NaN,NaN,NaN,NaN,NaN,6.022008e+10,20221031.0,103352.0,20220311,NaN,NaN,NaN,1.049990e+09,10,10.0,06,32.0,06,20221103.0,4.0,1430.0,85.0,2.0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
110955,20221103,4,2A,A,17,이상혁,920219-1000000,NaN,9103029.0,0,3,NaN,6.022027e+10,1.099624e+09,NaN,NaN,NaN,NaN,NaN,6.022027e+10,20221101.0,112726.0,20221028,NaN,NaN,NaN,1.099624e+09,10,10.0,06,32.0,06,20221103.0,4.0,1430.0,91.0,0.0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
110956,20221103,4,2A,A,18,WENSHUNAI,700926-6000000,NaN,9103029.0,0,3,NaN,6.022025e+10,NaN,NaN,NaN,NaN,NaN,NaN,6.022025e+10,20221027.0,111843.0,20220929,NaN,NaN,NaN,NaN,10,10.0,06,32.0,06,20221103.0,4.0,1430.0,84.0,0.0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
110957,20221103,4,2A,A,19,이경민,011217-3000000,NaN,2107064.0,100,10,NaN,7.322066e+10,1.050207e+09,NaN,NaN,NaN,NaN,NaN,7.322066e+10,20221101.0,122841.0,20221101,NaN,NaN,NaN,1.050207e+09,10,10.0,06,32.0,06,20221103.0,4.0,1430.0,92.0,1.0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110958,20221103,4,2A,A,20,정지현,971029-1000000,NaN,2107064.0,68,2,NaN,6.022027e+10,1.077542e+09,NaN,NaN,NaN,NaN,NaN,6.022027e+10,20221103.0,73108.0,20221026,NaN,NaN,NaN,1.077542e+09,10,10.0,06,32.0,06,20221103.0,4.0,1430.0,83.0,0.0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN

In [65]:
DexamD.columns

Index(['ExamDate', 'Class', 'License', 'ExamType', 'AppNo', 'TestNo', 'Score',
       'ExamResult', 'WrongFlag', 'ManualFlag', 'StartTime', 'FinishTime',
       'ParkTime', 'ParkFinishTime', 'BeforeStart', 'DrivePosture', 'Start',
       'SpeedSustain', 'Brake', 'Steering', 'CarBody', 'Navigate', 'ChangeDir',
       'PassCross', 'Parking', 'Etc', 'FailCode', 'MapID', 'CarID',
       'OfficerID', 'RoadFlag', 'ParkFlag', 'BeltFlag', 'HandiFlag', 'MacAddr',
       'TotalDis'],
      dtype='object')

# 도로주행코스

In [12]:
tmp = pd.read_csv('../../../011.데이터/08.LICENSE_ETC/testxml.csv')

,Table,HakCode,MapID,MapPosID,PosInfo,PosInfo2,PosInfo3,PosInfo4,Latitude,Longtitude,Angle,Distance,SpeedLimit,Icon,Voice,Voice2
0,강서시험장,3,A,1,2,0,0,0,37.549753,126.820102,230,9,50,1,"3,1","3,1"
1,강서시험장,3,A,2,0,0,0,0,37.549703,126.820028,226,14,50,23,0,0
2,강서시험장,3,A,3,0,0,0,0,37.549616,126.819913,231,20,50,31,"304,101,304","304,101,304"
3,강서시험장,3,A,4,5,1,2,0,37.549505,126.819741,230,15,50,31,0,0
4,강서시험장,3,A,5,5,0,3,0,37.549417,126.819609,216,13,50,31,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10504,전남시험장,21,F,132,0,0,0,0,35.006750,126.703271,35,34,0,0,NaN,NaN
10505,전남시험장,21,F,133,0,0,0,0,35.007000,126.703483,60,101,0,0,NaN,NaN
10506,전남시험장,21,F,134,0,0,0,0,35.007453,126.704443,76,39,0,0,"407,502","407,502"
10507,전남시험장,21,F,135,0,0,0,0,35.007539,126.704853,82,17,0,0,NaN,NaN
10508,전남시험장,21,F,136,15,0,0,0,35.007561,126.705042,0,0,60,56,NaN,NaN

In [5]:
process_xml_files('../../../011.데이터/08.LICENSE_ETC/data/','./')

In [11]:
input_path = '../../../011.데이터/08.LICENSE_ETC/data'
for path in os.listdir(input_path):
        for site in os.listdir(os.path.join(input_path, path)):
            xml_file_path = os.path.join(input_path, path, site)
            print(path)

강서시험장
도봉시험장
안산시험장
용인시험장
원주시험장
의정부시험장
인천시험장
전남시험장

In [2]:
tmp = pd.read_csv('../../../011.데이터/09.ETC/도봉_주정차내역.csv')

In [3]:
tmp

,관할관서,단속일시,단속동,단속장소,위반내용,차종,단속구분,견인지시,어린이보호구역_구분
0,도봉구,20200101,도봉1동,공영주차장건너편,보도,승용,CCTV,미견인,일반
1,도봉구,20200101,창동,335-2,보도,승합,안전신문고(앱),미견인,일반
2,도봉구,20200101,방학동,735 성원아파트,횡단보도,승용,서울스마트불편신고,미견인,일반
3,도봉구,20200101,창동,585-84,보도,승용,서울스마트불편신고,미견인,일반
4,도봉구,20200101,쌍문동,88-115,보도,승용,서울스마트불편신고,미견인,일반
...,...,...,...,...,...,...,...,...,...
166956,도봉구,20230731,쌍문동,백운중학교 (대영약국,가락공판장),주차금지(황색점선)구역,화물4톤이하,고정형CCTV,미견인
166957,도봉구,20230731,창동,창일초등학교 정문 (봉답기사식당),주정차금지(황색실선)구역,화물4톤이하,고정형CCTV,미견인,어린이보호구역
166958,도봉구,20230731,도봉동,다락원체육공원 평화문화진지 근처,주정차금지(황색실선)구역,특수,고정형CCTV,미견인,일반
166959,도봉구,20230731,쌍문동,신도봉중학교 앞 삼거리(도봉로115길 16),주차금지(황색점선)구역,화물4톤이하,고정형CCTV,미견인,일반
166960,도봉구,20230731,도봉동,투웨니퍼스트 앞 (도봉로180길 38),주차금지(황색점선)구역,특수,고정형CCTV,미견인,일반

In [13]:
tmp =pd.read_csv('../../../011.데이터/08.LICENSE_ETC/RD_LIC_COS_GIS.csv')

In [14]:
tmp.head()

,Table,HakCode,MapID,MapPosID,PosInfo,PosInfo2,PosInfo3,PosInfo4,Latitude,Longtitude,Angle,Distance,SpeedLimit,Icon,Voice,Voice2
0,강서시험장,3,A,1,2,0,0,0,37.549753,126.820102,230,9,50,1,"3,1","3,1"
1,강서시험장,3,A,2,0,0,0,0,37.549703,126.820028,226,14,50,23,0,0
2,강서시험장,3,A,3,0,0,0,0,37.549616,126.819913,231,20,50,31,"304,101,304","304,101,304"
3,강서시험장,3,A,4,5,1,2,0,37.549505,126.819741,230,15,50,31,0,0
4,강서시험장,3,A,5,5,0,3,0,37.549417,126.819609,216,13,50,31,0,0

In [15]:
ep = pd.read_csv('../../../011.데이터/07.ROAD/TB_EXAMPOINT_202309221431.csv')
rer = pd.read_csv('../../../011.데이터/07.ROAD/TB_RERROADEXP_202309221431.csv')

In [22]:
ep[(ep['EXM_LICEN_NO'] == 59210385191)&(ep['EXAMDATE'] == 20220105)]

,EXM_LICEN_NO,EXAMDATE,CLASS,LICENSE,EXAMTYPE,APPNO,TESTNO,COURSEFLAG,POINTCODE,POINTTIME,CANCELFLAG,REFFLAG,REFVALUE,MANUALFLAG,CANCELREASON,LATITUDE,LONGITUDE
0,59210385191,20220105,4,2A,A,10,1,1,32,2022-01-05 14:47:04.000,N,0,0,N,NaN,37.578970,126.880617
1,59210385191,20220105,4,2A,A,10,1,1,101,2022-01-05 14:48:42.000,N,0,0,N,NaN,37.578307,126.881932
2,59210385191,20220105,4,2A,A,10,1,1,61,2022-01-05 14:49:00.000,N,0,0,Y,NaN,37.578260,126.881887
3,59210385191,20220105,4,2A,A,10,1,1,41,2022-01-05 14:51:16.000,N,0,0,N,NaN,37.578707,126.878853
4,59210385191,20220105,4,2A,A,10,1,1,23,2022-01-05 14:55:45.000,N,0,0,Y,NaN,37.574323,126.886207
5,59210385191,20220105,4,2A,A,10,1,1,102,2022-01-05 14:56:57.000,N,0,0,N,NaN,37.574253,126.886433

In [21]:
rer[rer['EXM_LICEN_NO'] == 59210385191)]

,EXM_LICEN_NO,RECEIVE_DATE,RECEIVE_TIME,LICN_PRT_DATE,RESIDENT_DATE,RESIDENT_NO,RESIDENT_NAME,RES_PHONE_NO,PROC_EXM_CODE,RES_EXM_CODE,EXM_CODE,RES_CLS_CODE,LICN_CON_CODE,RESPOND_DATE,RESPOND_TIME,RES_START_TIME,EXM_NO,RECV_KIND_CODE,WEB_RECV_OPT,COURSE,OBSRV_EXM_NO,OBSRV_RESIDENT_DATE,OBSRV_RESIDENT_NO,OBSRV_RESIDENT_NAME,OBSRV_PHONE_NO,RESPOND_PNT,EXM_JUDG_CODE,WRONG_CNT,MANUAL_OPT,CAR_STR_TIME,CAR_END_TIME,PARK_STR_TIME,PARK_END_TIME,BEF_DECT_PNT,DRV_DECT_PNT,STR_DECT_PNT,SPD_DECT_PNT,BRAKE_DECT_PNT,STER_DECT_PNT,BODY_DECT_PNT,NEVI_DECT_PNT,CHG_DECT_PNT,TURN_DECT_PNT,PARK_DECT_PNT,ETC_DECT_PNT,FAIL_CODE,CAR_NO,RSLT_ENT_DATE,RSLT_ENT_ID,RSLT_ENT_NAME,ROAD_EXM_OPT,PARK_EXM_OPT,LIFEBELT_OPT,HANDICAP_OPT,TABLET_IP_ADDR,POINT_OPT,ENTRY_PLACE,ENTRY_DATE,ENTRY_TIME,ENTRY_NAME,UPDATE_DATE,UPDATE_TIME,DOWNLOAD_YN,AUTO_YN,PARK_ENTER_TIME,SPEED_CHECK40,SPEED_CHECK50,SPEED_CHECK60,SPEED_CHECK70,DISTANCE
6678,59210385191,20220105,153649,20211230,881020,6760021,JIGUIXIANG,NaN,8,8,06,32,06,20220110,2,1000,4120,2,NaN,C,4102.0,1207.0,4000000.0,이신혜,1.047122e+09,93.0,1,0.0,N,101358.0,103445.0,0.0,0.0,0,0,0,0,0,7,0,0,0,0,0,0,0.0,2-12(9174),20220110.0,1112106.0,최유정,Y,N,N,N,D0:7F:A0:CF:E7:99,2,8,20220110,605,CRON,20220110.0,113202.0,Y,Y,0.0,0.0,0.0,0.0,0.0,NaN
7414,59210385191,20211230,154410,20211230,881020,6760021,JIGUIXIANG,NaN,9,8,06,32,06,20220105,4,1430,4117,1,NaN,D,4102.0,910212.0,1000000.0,김대영,1.092203e+09,59.0,2,0.0,N,144635.0,145707.0,0.0,0.0,0,0,15,5,0,7,0,0,0,14,0,0,0.0,2-6(4126),20220105.0,8405032.0,조정연,Y,N,N,N,D0:B1:28:05:04:03,2,9,20220105,605,CRON,20220105.0,160054.0,Y,Y,0.0,0.0,0.0,0.0,0.0,NaN

In [23]:
taas = pd.read_csv('../../../011.데이터/01.TAAS/TAAS데이터/taas001h_2018_2022.csv')
taas_cd = pd.read_excel('../../../011.데이터/01.TAAS/TAAS데이터/tass_code.xlsx')

In [26]:
col_cd = {key : value for key,value in zip(taas_cd['영문컬럼'],taas_cd['컬럼명'])}

In [29]:
taas.columns = [col_cd.get(x) for x in taas.columns]

In [30]:
taas.head()

,본표번호,경찰서코드,통계년도,발생지시군구코드,주거지시군구코드1,주거지시군구코드2,None,None,발생일시,발생요일,주야,사고내용,사망자수,중상자수,경상자수,부상신고자수,사고유형,관련차량대수,운전자성별1,운전자성별2,운전자나이1,운전자나이2,학생사고1(16년이전 운전자직업),학생사고2(16년이전 운전자직업),운전자면허종별1,운전자면허종별2,면허경과년수1,면허경과년수2,음주운전1,음주운전2,보호장구착용여부1,보호장구착용여부2,법규위반내용1,법규위반내용2,행동유형1,행동유형2,신체상해정도1,신체상해정도2,신체상해주부위1,신체상해주부위2,당사자종별1,당사자종별2,차량용도별1,차량용도별2,보험가입상황1,보험가입상황2,도로종류,노선번호,도로형태,특정도로,도로선형,기상상태,노면상태,중앙분리시설,보차도분리시설,고속도로도로위치,대형사고여부,사망사고여부,중상사고여부,경상사고여부,부상신고사고여부,음주운전사고여부,여성운전자사고여부,차대사람사고여부,차대차사고여부,차량단독사고여부,횡단보도사고여부,교차로사고여부,일반국도사고여부,고속국도사고여부,버스전용차로사고여부,사업용차량사고여부,비사업용차량사고여부,화물차사고여부,이륜차사고여부,택시사고여부,시내버스사고여부,뺑소니사고여부,무면허운전사고여부,무보험차량사고여부,연령별어린이사고여부,보행어린이사고여부,어린이보호구역사고여부,학년별어린이사고여부,고령층사고여부,고령운전자사고여부,중상이상사고여부,타지역구분,발생시간,특수사고 뺑소니,특수사고 역주행,특수사고 긴급자동차,특수사고 개문발차,특수사고 급발진(제외됨),특수사고 연쇄사고(제외됨),특수사고 군용차,특수사고 차량화재(제외됨),특수사고 신체장애자(제외됨),특수사고 급성질환(제외됨),특정도로 자동차전용도로,특정도로 가로변버스전용차로(버스전용차로),특정도로 중앙버스전용차로,특정도로 자전거도로(제외됨),특정도로 가변차로,특정도로 하이패스차로,특정도로 일방통행도로,특정도로 어린이보호구역,특정도로 노인보호구역,특정도로 장애인보호구역,보차도분리시설 노면표시,보차도분리시설 연석,보차도분리시설 가드레일(제외됨),보차도분리시설 휀스(제외됨),보차도분리시설 기타분리시설,운전자국적1,운전자국적2,음주운전행정처분횟수1,음주운전행정처분횟수2,차명1,차명2,교차로형태,통합DB 사고번호 (2005년 부터 값있음),법규위반내용1_분류1,법규위반내용2_분류1,특수사고 도로내동물사고(17년추가),특수사고 대리운전(17년추가),특수사고 전기자동차(17년추가),특정도로 자전거전용도로(17년추가),특정도로 자전거우선도로(17년추가),특정도로 자전거전용차로(17년추가),특정도로 자전거보행자겸용도로(17년추가),특정도로 당_30구역(17년추가),특정도로 기타(17년추가)(제외됨),보차도분리시설 가드레일/휀스(17년추가),왕복차로수(17년추가),None
0,2018000965,1104,2018,1102,1102,1102,127.015140,37.562809,2018100906,3,1,4,0,0,0,1,25,2,2,1,77,38,0,00,99,02,99,08,00,00,9,4,132,903,1,01,5,4,0,03,98,05,98,27,4,2,3,0,5,NaN,9,1,1,1.0,NaN,0.0,2,2,2,2,1,2,1,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,2,1,2,11,20,0,0,0,0,NaN,NaN,0,NaN,NaN,NaN,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,NaN,0,1,01,NaN,NaN,NaN,NaN,1,2018100900100092,13201,90301.0,0,0,0,0,0,0.0,0,0,NaN,0,0,NaN
1,2018001068,1104,2018,1102,1102,1106,127.014442,37.551819,2018110419,1,2,3,0,0,2,0,26,3,1,1,66,53,0,00,2,05,8,08,03,99,1,1,132,903,8,10,5,3,0,08,3,01,26,21,2,1,3,0,5,NaN,8,1,1,6.0,NaN,0.0,2,2,2,1,2,1,2,2,1,2,2,2,2,2,2,2,1,1,2,2,2,2,2,2,2,2,2,2,2,1,2,11,3,0,0,0,0,NaN,NaN,0,NaN,NaN,NaN,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,NaN,0,1,01,NaN,NaN,NaN,NaN,1,2018110400100433,13201,90301.0,0,0,0,0,0,0.0,0,0,NaN,0,0,NaN
2,2018000635,1104,2018,1102,9900,2404,127.011143,37.555906,2018070122,1,2,2,0,1,0,0,5,1,9,1,999,51,99,00,99,99,99,99,99,99,9,7,132,903,99,24,9,2,0,14,99,12,99,42,9,5,3,0,5,NaN,9,1,2,1.0,NaN,0.0,2,2,1,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,99,15,0,0,0,0,NaN,NaN,0,NaN,NaN,NaN,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,NaN,0,9,01,NaN,NaN,NaN,NaN,1,2018070100100439,13201,90301.0,0,0,0,0,0,0.0,0,0,NaN,0,0,NaN
3,2018001034,1104,2018,1102,1107,####,127.002309,37.566640,2018072805,7,2,2,0,1,0,0,37,1,1,#,45,0,0,##,1,##,8,##,00,##,3,#,132,###,1,##,5,#,0,##,2,##,1,##,3,#,3,0,5,NaN,9,1,1,1.0,NaN,0.0,2,2,1,2,2,2,2,2,2,1,2,2,2,2,2,1,2,2,2,2,1,2,2,2,2,2,2,2,2,2,1,12,28,0,0,0,0,NaN,NaN,0,NaN,NaN,NaN,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,NaN,0,1,##,NaN,NaN,NaN,NaN,1,2018072800100074,13201,NaN,0,0,0,0,0,0.0,0,0,NaN,0,0,NaN
4,2018001166,1104,2018,1102,1105,1304,127.007521,37.569601,2018120615,5,1,3,0,0,1,0,22,3,1,1,72,29,0,00,2,02,8,07,00,00,1,4,134,903,10,01,5,3,0,09,1,05,6,27,3,2,3,0,5,NaN,9,1,1,5.0,NaN,0.0,2,2,2,1,2,2,2,2,1,2,2,2,2,2,2,1,2,2,2,1,2,2,2,2,2,2,2,2,2,1,2,12,10,0,0,0,0,NaN,NaN,0,NaN,NaN,NaN,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,NaN,0,1,01,NaN,NaN,NaN,NaN,1,2018120600100342,13408,90301.0,0,0,0,0,0,0.0,0,0,NaN,0,0,NaN